const SUPABASE_URL='https://wuflhovtbvocjpalblab.supabase.co';
const SUPABASE_KEY='sb_publishable_58URlpq7aVTG1JyFydodWw_5EiWSPWD';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const seed=[
 {id:crypto.randomUUID(),name:'Nadia Pratama',organization:'Universitas Nusantara',email:'nadia@example.com',phone:'081234567890',source:'LinkedIn',status:'qualified',followup:new Date(Date.now()+86400000).toISOString(),notes:'Membutuhkan sistem career center.'},
 {id:crypto.randomUUID(),name:'Rizky Maulana',organization:'Yayasan Cendekia',email:'rizky@example.com',phone:'081298765432',source:'Referral',status:'contacted',followup:new Date(Date.now()-86400000).toISOString(),notes:'Follow-up proposal program.'},
 {id:crypto.randomUUID(),name:'Salsa Putri',organization:'SMA Global Mandiri',email:'salsa@example.com',phone:'081277733344',source:'Event',status:'new',followup:'',notes:''}
];
let leads=JSON.parse(localStorage.getItem('optima_leads')||'null')||seed;
let currentUser=JSON.parse(sessionStorage.getItem('optima_user')||'null');
const save=()=>localStorage.setItem('optima_leads',JSON.stringify(leads));
const label=s=>({new:'New',contacted:'Contacted',qualified:'Qualified',nurturing:'Nurturing',converted:'Converted',unqualified:'Unqualified'}[s]||s);
function showApp(user){currentUser=user;sessionStorage.setItem('optima_user',JSON.stringify(user));$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=user.name||user.email||'Optima User';$('#avatar').textContent=(user.name||user.email||'O')[0].toUpperCase();renderAll()}
function logout(){sessionStorage.removeItem('optima_user');location.reload()}
async function login(email,password){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Login gagal');return {name:data.user?.user_metadata?.full_name||email.split('@')[0],email,token:data.access_token,mode:'supabase'}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const alert=$('#loginAlert');alert.classList.add('hidden');try{showApp(await login($('#email').value,$('#password').value))}catch(err){alert.textContent=err.message;alert.classList.remove('hidden')}});
$('#demoButton').addEventListener('click',()=>showApp({name:'Demo OPTIMA',email:'demo@optima.id',mode:'demo'}));$('#logoutButton').addEventListener('click',logout);
function setView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$(`#${name}View`).classList.remove('hidden');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const map={dashboard:['Ringkasan Operasional','Dashboard','Pantau performa dan tindakan prioritas hari ini.'],leads:['CRM Database','CRM Leads','Kelola prospek, status, dan rencana follow-up.'],followups:['Action Center','Follow-up Center','Selesaikan tindak lanjut tepat waktu.']};[$('#pageEyebrow').textContent,$('#pageTitle').textContent,$('#pageSubtitle').textContent]=map[name];$('#addLeadButton').classList.toggle('hidden',name==='followups');}
$$('.nav').forEach(n=>n.addEventListener('click',()=>setView(n.dataset.view)));$$('[data-go]').forEach(n=>n.addEventListener('click',()=>setView(n.dataset.go)));
function renderAll(){save();renderDashboard();renderLeads();renderFollowups()}
function renderDashboard(){const now=Date.now();$('#totalLead').textContent=leads.length;$('#qualifiedLead').textContent=leads.filter(x=>x.status==='qualified').length;$('#activeClient').textContent=leads.filter(x=>x.status==='converted').length;$('#overdueCount').textContent=leads.filter(x=>x.followup&&new Date(x.followup).getTime()<now&&x.status!=='converted').length;$('#recentLeads').innerHTML=leads.slice(-5).reverse().map(x=>`<div class="lead-line"><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.organization||'Individu')} · ${escapeHtml(x.source)}</small></div><span class="badge">${label(x.status)}</span></div>`).join('')||'<p class="muted">Belum ada lead.</p>';const statuses=['new','contacted','qualified','nurturing','converted'];const max=Math.max(1,...statuses.map(s=>leads.filter(x=>x.status===s).length));$('#pipelineChart').innerHTML=statuses.map(s=>{const n=leads.filter(x=>x.status===s).length;return `<div class="pipeline-row"><span>${label(s)}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`}).join('')}
function filtered(){const q=$('#searchLead').value.toLowerCase(),s=$('#statusFilter').value;return leads.filter(x=>(!q||`${x.name} ${x.organization}`.toLowerCase().includes(q))&&(!s||x.status===s))}
function renderLeads(){const rows=filtered();$('#leadRows').innerHTML=rows.map(x=>`<tr><td><div class="row-name">${escapeHtml(x.name)}</div><div class="row-sub">${escapeHtml(x.email||x.phone||'-')}</div></td><td>${escapeHtml(x.organization||'-')}</td><td><span class="badge">${label(x.status)}</span></td><td>${escapeHtml(x.source)}</td><td>${x.followup?new Date(x.followup).toLocaleString('id-ID'):'-'}</td><td><button class="mini-button" onclick="advance('${x.id}')">Update status</button></td></tr>`).join('')||'<tr><td colspan="6" style="text-align:center;color:#6b7b89;padding:36px">Data tidak ditemukan.</td></tr>'}
function renderFollowups(){const rows=leads.filter(x=>x.followup&&x.status!=='converted').sort((a,b)=>new Date(a.followup)-new Date(b.followup));$('#followupRows').innerHTML=rows.map(x=>{const overdue=new Date(x.followup)<new Date();return `<tr><td><div class="row-name">${escapeHtml(x.name)}</div><div class="row-sub">${escapeHtml(x.organization||'-')}</div></td><td>${escapeHtml(x.notes||'Follow-up lead')}</td><td class="${overdue?'danger-text':''}">${new Date(x.followup).toLocaleString('id-ID')}</td><td><span class="badge">${overdue?'Overdue':'Upcoming'}</span></td><td><button class="mini-button" onclick="completeFollowup('${x.id}')">Selesaikan</button></td></tr>`}).join('')||'<tr><td colspan="5" style="text-align:center;color:#6b7b89;padding:36px">Tidak ada follow-up aktif.</td></tr>'}
window.advance=id=>{const order=['new','contacted','qualified','nurturing','converted'];const x=leads.find(l=>l.id===id);x.status=order[Math.min(order.indexOf(x.status)+1,order.length-1)];renderAll()};window.completeFollowup=id=>{const x=leads.find(l=>l.id===id);x.followup='';renderAll()};
$('#searchLead').addEventListener('input',renderLeads);$('#statusFilter').addEventListener('change',renderLeads);$('#addLeadButton').addEventListener('click',()=>$('#leadDialog').showModal());
$('#leadForm').addEventListener('submit',e=>{const submit=e.submitter;if(submit?.value==='cancel')return; e.preventDefault();const d=Object.fromEntries(new FormData(e.target));leads.push({id:crypto.randomUUID(),...d});e.target.reset();$('#leadDialog').close();renderAll();setView('leads')});
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
if(currentUser)showApp(currentUser);
